spring:
  profiles:
    include: "default"

server:
  port: "${SERVER_PORT}"

keycloak:
  auth-server-url: "${KEYCLOAK_AUTH_URL}"
  realm: "${KEYCLOAK_REALM}"
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  resource: "${KEYCLOAK_CLIENT_ID}"
  credentials:
    secret: "${KEYCLOAK_CLIENT_SECRET}"

